### PR TITLE
Prevent waves causing UI, units, buildings disappear

### LINKED ISSUE #45: Water waves can cause UI and buildings to disappear entirely
It was big trouble for me at first as I not yet knew where the logs are. So I grepped the code like crazy for water references because it seemed to happen whenever water was on the view.

I changed this and that with no effect, even looked into shaders ... until I finally stumbled across waves. And the logs showed up, too. Dumb me. There is was written, clear and obvious.

Looking for the code made me learn the code base, so it wasn't wasted.  :-)

Strong project! Really epic! Like the real game. Now I can finally show it to my little brother. As the CDs from back then no longer work on Windows (for me). And we like Linux more :)) So many many thanks to you guys 'n gals
```

Main draw handler cought throwable:
java.lang.ArithmeticException: / by zero
        at jsettlers.graphics.map.draw.MapObjectDrawer.drawWaves(MapObjectDrawer.java:1066)
        at jsettlers.graphics.map.draw.MapObjectDrawer.drawObject(MapObjectDrawer.java:509)
        at jsettlers.graphics.map.draw.MapObjectDrawer.drawMapObject(MapObjectDrawer.java:261)
        at jsettlers.graphics.map.MapContent.drawTile(MapContent.java:608)
        at jsettlers.graphics.map.MapContent.drawMain(MapContent.java:574)
        at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:335)
        at go.graphics.region.Region.drawRegion(Region.java:97)
        at go.graphics.area.Area.drawArea(Area.java:93)
        at go.graphics.swing.AreaContainer.draw(AreaContainer.java:75)
        at go.graphics.swing.contextcreator.JAWTContextCreator$1.paint(JAWTContextCreator.java:111)
        at go.graphics.swing.contextcreator.JAWTContextCreator$1.update(JAWTContextCreator.java:81)
        at java.desktop/sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
        at java.desktop/sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:52)
        at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:232)
        at java.desktop/sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:555)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5062)

```

### PR DESCRIPTION
**Pull request by faerietree**
Fix #45

### CODE REVIEW

**Comment by paulwedeck** [comment]
Thank you for the contribution.
If again encounter such a bug feel free to just open an issue.
May I ask why your installation doesn't have waves? All GFX directories that I know of have them

**Comment by HiranChaudhuri** [comment]
Would it be huge effort to have a method that at startup checks if for all the configured civilisations the required resources are available? That could help us figure out problems early.

**Comment by paulwedeck** [comment]
First of all this isn't about civilization specifc textures.
I remember having this discussion in a different issue: Yes, we can at least partially check if the civilization is available but the big question if what we do with this information.
Its completely possible to run jsettlers without graphics at all (e.g. unit tests) and we can't prevent mp games with missing civilization textures. The only thing we can do is to check it and notify the user that something is going to be wrong

**Comment by HiranChaudhuri** [comment]
Yes a notification and some entry in the logs would be sufficient. After all there is no procedure to automatically fix broken or missing files. But once we know the game files are broken we could ask the user to reinstall the game.

And true: Waves are not civilisation specific.

**Pull request merged**
